default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "password") %>
  host: <%= ENV.fetch("MYSQL_HOST", "db") %>

development:
  <<: *default
  database: rails_ecs_fargate2_development

test:
  <<: *default
  database: rails_ecs_fargate2_test

production:
  <<: *default
  database: rails_ecs_fargate2_production
  username: rails_ecs_fargate2
  password: <%= ENV['RAILS_ECS_FARGATE2_DATABASE_PASSWORD'] %>
